In [1]:
import torch
from torch import linalg 

In [2]:
# addition
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
print(A.shape)
A

torch.Size([2, 3])


tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [6]:
A/A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [7]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 3.],
        [12.]])

In [8]:
X.sum(axis=0)

NameError: name 'X' is not defined

In [ ]:
X.sum(axis=1)

In [9]:
X.sum(axis=2)

NameError: name 'X' is not defined

In [28]:
linalg.norm(X)

tensor(14.4928)

In [10]:
A = torch.randn(2**10, 2**16)
B = torch.randn(2**16, 2**5)
C = torch.randn(2**5, 2**14)


In [11]:
torch.matmul(A,B).shape

torch.Size([1024, 32])

In [12]:
C.shape

torch.Size([32, 16384])

In [13]:
torch.matmul(torch.matmul(A,B), C).shape

torch.Size([1024, 16384])

In [14]:
torch.matmul(torch.matmul(A,B), C)

tensor([[-3284.8647, -2201.9680, -1667.5922,  ...,  1693.3125,   345.2137,
          -891.7568],
        [  467.6843,  2318.1606,  2634.0837,  ...,   455.5876,   -53.5335,
            46.4738],
        [   46.1107, -2598.3245,  1976.4624,  ...,   400.4944,  2859.9399,
          1801.3655],
        ...,
        [-2501.7676,  2871.3843, -2678.1204,  ...,  -537.9288,  -890.1832,
         -1205.9635],
        [ -520.1506, -2426.2834,    10.7511,  ..., -1010.0280, -2079.6445,
           693.5912],
        [  266.5056,   707.7820, -2418.2136,  ...,   286.4916,   677.3766,
          -236.9149]])

In [15]:
torch.matmul(B,C).shape

torch.Size([65536, 16384])

In [16]:
A.shape

torch.Size([1024, 65536])

In [17]:
torch.matmul(A, torch.matmul(B,C)).shape

torch.Size([1024, 16384])

In [19]:
torch.matmul(A, torch.matmul(B,C))

tensor([[-3284.8635, -2201.9678, -1667.5925,  ...,  1693.3123,   345.2130,
          -891.7582],
        [  467.6850,  2318.1599,  2634.0823,  ...,   455.5884,   -53.5346,
            46.4748],
        [   46.1105, -2598.3250,  1976.4633,  ...,   400.4951,  2859.9395,
          1801.3656],
        ...,
        [-2501.7661,  2871.3850, -2678.1199,  ...,  -537.9279,  -890.1833,
         -1205.9635],
        [ -520.1510, -2426.2847,    10.7511,  ..., -1010.0274, -2079.6450,
           693.5921],
        [  266.5059,   707.7816, -2418.2126,  ...,   286.4914,   677.3776,
          -236.9149]])

In [55]:
A = torch.randn(2**10, 2**16)
B = torch.randn(2**16, 2**5)
C = torch.randn(2**5, 2**16)


In [20]:
torch.matmul(A,B)

tensor([[ 275.0225,  -85.5485,  -15.6981,  ...,  235.1223,  110.1394,
          -35.9472],
        [ -29.3260,  137.1320,  103.7480,  ..., -438.2172,  267.4696,
          104.8698],
        [ 146.0393,  156.2763,  314.0150,  ...,  216.5195,  147.6075,
          347.6027],
        ...,
        [-189.1582, -352.7052,  117.5308,  ..., -171.8876, -250.0430,
          195.1603],
        [ 327.5074,   39.7277, -227.5168,  ..., -315.6818, -336.3789,
         -356.1294],
        [ 221.1636,   90.2099,  109.0862,  ..., -527.6683, -150.5528,
         -213.0869]])

In [21]:
C = B.T
torch.matmul(A,C.T)

tensor([[ 275.0225,  -85.5485,  -15.6981,  ...,  235.1223,  110.1394,
          -35.9472],
        [ -29.3260,  137.1320,  103.7480,  ..., -438.2172,  267.4696,
          104.8698],
        [ 146.0393,  156.2763,  314.0150,  ...,  216.5195,  147.6075,
          347.6027],
        ...,
        [-189.1582, -352.7052,  117.5308,  ..., -171.8876, -250.0430,
          195.1603],
        [ 327.5074,   39.7277, -227.5168,  ..., -315.6818, -336.3789,
         -356.1294],
        [ 221.1636,   90.2099,  109.0862,  ..., -527.6683, -150.5528,
         -213.0869]])

In [22]:
C.T.shape

torch.Size([65536, 32])

In [23]:
A.shape

torch.Size([1024, 65536])

In [24]:
A = torch.randn(2**10, 2**20)
B = torch.randn(2**10, 2**20)
C = torch.randn(2**10, 2**20)

In [25]:
B.shape

torch.Size([1024, 1048576])

In [26]:
tensor = torch.stack((A,B,C))

In [27]:
tensor.shape

torch.Size([3, 1024, 1048576])

In [28]:
B

tensor([[ 0.4971,  1.0003,  0.3834,  ...,  0.4341, -0.9110,  1.1060],
        [ 0.9218,  0.5049,  1.0555,  ..., -1.0749, -3.2097, -0.1273],
        [-0.7699, -2.2897,  1.5812,  ..., -0.2564, -0.1347,  0.0628],
        ...,
        [-1.6507,  0.1397, -1.4212,  ..., -0.5175, -0.0439,  0.5409],
        [ 0.6202,  0.2403, -0.7238,  ..., -0.0383, -0.2474, -0.7272],
        [-1.3233, -0.1735, -1.6258,  ..., -0.4876, -1.3748, -1.4001]])

In [30]:
tensor[1]

tensor([[ 0.4971,  1.0003,  0.3834,  ...,  0.4341, -0.9110,  1.1060],
        [ 0.9218,  0.5049,  1.0555,  ..., -1.0749, -3.2097, -0.1273],
        [-0.7699, -2.2897,  1.5812,  ..., -0.2564, -0.1347,  0.0628],
        ...,
        [-1.6507,  0.1397, -1.4212,  ..., -0.5175, -0.0439,  0.5409],
        [ 0.6202,  0.2403, -0.7238,  ..., -0.0383, -0.2474, -0.7272],
        [-1.3233, -0.1735, -1.6258,  ..., -0.4876, -1.3748, -1.4001]])